GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Harry Potter",
    "author": "Rowling",
    "url": "https://vi.wikipedia.org/wiki/Harry_Potter",
    "likes": 100
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Doraemon",
    "author": "Fujiko Fujio",
    "url": "https://en.wikipedia.org/wiki/Doraemon_(character)",
    "likes": 1000
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A Brief History of Time",
    "author": "Stephen Hawking",
    "url": "https://en.wikipedia.org/wiki/A_Brief_History_of_Time",
    "likes": 1000
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "url": "https://mongoosejs.com/docs/validation.html",
    "likes": 123
}

###
DELETE http://localhost:3003/api/blogs/64440a3a9141e95c0497bc66

###
PUT http://localhost:3003/api/blogs/642865c2974078c6130ba844
Content-Type: application/json

{
    "title": "Harry Potter",
    "author": "Rowling",
    "url": "https://vi.wikipedia.org/wiki/Harry_Potter",
    "likes": 123
}

###
PUT http://localhost:3003/api/blogs/642865c2974078c6130ba844
Content-Type: application/json

{
    "title": "",
    "author": "",
    "url": "https://vi.wikipedia.org/wiki/Harry_Potter",
    "likes": 123
}

###
PUT http://localhost:3003/api/blogs/64440a3a9141e95c0497bc66
Content-Type: application/json

{
    "title": "Harry Potter",
    "author": "Rowling",
    "url": "https://vi.wikipedia.org/wiki/Harry_Potter",
    "likes": 321
}